version: "3.9"

services:
  app:
    build: .
    container_name: chat_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    container_name: chat_redis
    ports:
      - "6379:6379"
    restart: always